export enum IconPath {
  LOGO = '../../../assets/icons/logo.svg',
  BLUE_CHART = '../../../assets/icons/blue-chart.svg',
  GREEN_CHART = '../../../assets/icons/green-chart.svg',
  ORANGE_CHART = '../../../assets/icons/orange-chart.svg',
  PINK_CHART = '../../../assets/icons/pink-chart.svg',
  BED = '../../../assets/icons/bed.svg',
  LOCATION = '../../../assets/icons/location.svg',
  AREA = '../../../assets/icons/area.svg',
  UPLOAD = '../../../assets/icons/upload.svg',
  REAL_ESTATE = '../../../assets/icons/real-estate.svg',
  AVATAR_ICON = '../../../assets/icons/avatar.svg',
  TELEPHONE = '../../../assets/icons/telephone.svg',
  FLOOR = '../../../assets/icons/floor.svg',
  TYPE = '../../../assets/icons/type.svg',
  MAIL = '../../../assets/icons/mail.svg',
  AGENCY = '../../../assets/icons/agency.svg',
  CHECK = '../../../assets/icons/check.svg',
}